[id='start-process-specific-node-proc']

= Starting a business process from a specific node

In the process designer in {CENTRAL}, you can start a business process from a specific node after the business process is terminated. When a business process is terminated, the related data still exists and can be accessed to restore the business process. For example, this is useful when the business process termination did not proceed as desired.

.Procedure
. To start a business process from a specific node, use following command:
+
[source,code]
----
ProcessInstance startProcessFromNodeIds(String processId, CorrelationKey key, Map<String, Object> params, String... nodeIds);
----

.Starting business process command parameters
[cols="30%,70%", options="header"]
|===
|Parameter
|Description

|`processId`
|Indicates the unique identifier of a business process to be started

|`CorrelationKey`
|Indicates the unique correlation key to be assigned to a business process

|`params`
|Indicates the process variables

|`nodeIds`
|Indicates the list of node identifier that are triggered when a business process starts

|===
