[id='security-management-rest-api-permissions-ref_{context}']
= Permissions

The Security Management REST API supports the following endpoints for managing permissions granted to the groups, roles and users in {CENTRAL}. The Security Management REST API base URL is `http://SERVER:PORT/business-central/rest/`. All requests require HTTP Basic authentication or token-based authentication for the `rest-all` user role.

[GET] /groups/{groupName}/permissions::
+
--
Returns all permissions granted to a specified group.

.Request parameters
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`groupName`
|Name of the group whose permissions to be returned
|String
|Required
|===

.Example server response (JSON)
[source,json]
----
{
    "homePage": "HomePerspective",
    "priority": -10,
    "project": {
        "read": {
            "access": false,
            "exceptions": []
        },

    },
    "spaces": {
        "read": {
            "access": true,
            "exceptions": [
                "dsaddsa"
            ]
        },
    },
    "editor": {
        "read": {
            "access": false,
            "exceptions": [
                "GuidedDecisionTreeEditorPresenter"
            ]
        },
        "create": null,
        "update": null,
        "delete": null,
        "build": null
    },
    "pages": {
        "read": {
            "access": true,
            "exceptions": []
        },
        "build": null
    },
    "workbench": {
        "editDataObject": false,
        "plannerAvailable": false,
        "editGlobalPreferences": false,
        "editProfilePreferences": false,
        "accessDataTransfer": false,
        "jarDownload": true,
        "editGuidedDecisionTableColumns": true
    }
}
----
--

[GET] /roles/{roleName}/permissions::
+
--
Returns all permissions granted to a specified role.

.Request parameters
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`roleName`
|Name of the role whose permissions to be returned
|String
|Required
|===

.Example server response (JSON)
[source,json]
----
{
    "homePage": "HomePerspective",
    "priority": -10,
    "project": {
        "read": {
            "access": false,
            "exceptions": []
        },

    },
    "spaces": {
        "read": {
            "access": true,
            "exceptions": [
                "dsaddsa"
            ]
        },
    },
    "editor": {
        "read": {
            "access": false,
            "exceptions": [
                "GuidedDecisionTreeEditorPresenter"
            ]
        },
        "create": null,
        "update": null,
        "delete": null,
        "build": null
    },
    "pages": {
        "read": {
            "access": true,
            "exceptions": []
        },
        "build": null
    },
    "workbench": {
        "editDataObject": false,
        "plannerAvailable": false,
        "editGlobalPreferences": false,
        "editProfilePreferences": false,
        "accessDataTransfer": false,
        "jarDownload": true,
        "editGuidedDecisionTableColumns": true
    }
}
----
--

[GET] /users/{userName}/permissions::
+
--
Returns all permissions granted to a specified user.

.Request parameters
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`userName`
|Name of the user whose permissions to be returned
|String
|Required
|===

.Example server response (JSON)
[source,json]
----
{
    "homePage": "HomePerspective",
    "priority": -10,
    "project": {
        "read": {
            "access": false,
            "exceptions": []
        },

    },
    "spaces": {
        "read": {
            "access": true,
            "exceptions": [
                "dsaddsa"
            ]
        },
    },
    "editor": {
        "read": {
            "access": false,
            "exceptions": [
                "GuidedDecisionTreeEditorPresenter"
            ]
        },
        "create": null,
        "update": null,
        "delete": null,
        "build": null
    },
    "pages": {
        "read": {
            "access": true,
            "exceptions": []
        },
        "build": null
    },
    "workbench": {
        "editDataObject": false,
        "plannerAvailable": false,
        "editGlobalPreferences": false,
        "editProfilePreferences": false,
        "accessDataTransfer": false,
        "jarDownload": true,
        "editGuidedDecisionTableColumns": true
    }
}
----
--

[Post] /groups/{groupName}/permissions::
+
--
Updates the permissions of a specified group.

.Request parameters
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`groupName`
|Name of the group whose permissions to be updated
|String
|Required
|===

.Example request body (JSON)
[source,json]
----


    "project": {
        "create": true,
        "read": true,
        "delete": false,
        "update": false
    },
    "spaces": {
        "create": true,
        "read": true,
        "delete": false,
        "update": false
    },
    "editor": {
        "create": true,
        "read": true,
        "delete": false,
        "update": false
    },
    "pages": {
        "create": true,
        "read": false,
        "delete": false,
        "update": false,
        "exceptions": [
            {
                "name": "HomePerspective",
                "permissions": {
                    "create": true,
                    "read": true,
                    "delete": false
                }
            }
        ]
    }
}
----

.Example server response (JSON)
[source,json]
----
{
    "status": "OK",
    "message": "Group newGroup permissions are updated successfully."
}
----
--

[Post] /roles/{roleName}/permissions::
+
--
Updates the permissions of a specified role.

.Request parameters
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`roleName`
|Name of the role whose permissions to be updated
|String
|Required
|===

.Example request body (JSON)
[source,json]
----
{
    "project": {
        "create": true,
        "read": true,
        "delete": false,
        "update": false
    },
    "spaces": {
        "create": true,
        "read": true,
        "delete": false,
        "update": false
    },
    "editor": {
        "create": true,
        "read": true,
        "delete": false,
        "update": false
    },
    "pages": {
        "create": true,
        "read": false,
        "delete": false,
        "update": false,
        "exceptions": [
            {
                "name": "HomePerspective",
                "permissions": {
                    "create": true,
                    "read": true,
                    "delete": false
                }
            }
        ]
    }
}
----

.Example server response (JSON)
[source,json]
----
{
    "status": "OK",
    "message": "Role newRole permissions are updated successfully."
}
----
--
