[id='security-management-rest-api-users-ref_{context}']
= Users

The Security Management REST API supports the following endpoints for managing users in {CENTRAL}. The Security Management REST API base URL is `http://SERVER:PORT/business-central/rest/`. All requests require HTTP Basic authentication or token-based authentication for the `admin` user role.

[GET] /users::
+
--
Returns all users in {CENTRAL}.

.Example server response (JSON)
[source,json]
----
[
    "newUser",
    "user1",
    "user2",
]
----
--

[GET] /users/{userName}/groups::
+
--
Returns all groups assigned to a specified user.

.Request parameters
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`userName`
|Name of the user whose assigned groups to be returned
|String
|Required
|===

.Example server response (JSON)
[source,json]
----
[{
		"group1"
	},
	{
		"group2"
	}
]
----
--

[GET] /users/{userName}/roles::
+
--
Returns all roles assigned to a specified user.

.Request parameters
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`userName`
|Name of the user whose assigned roles to be returned
|String
|Required
|===

.Example server response (JSON)
[source,json]
----
[{
		"name": "process-admin"
	},
	{
		"name": "manager"
	},
	{
		"name": "admin"
	}
]
----
--

[POST] /users::
+
--
Creates a specified user with specified roles and groups.

.Example request body (JSON)
[source,json]
----
{
	"name": "newUser",
	"roles": ["roles.."],
	"groups": ["groups.."]
}
----

.Example server response (JSON)
[source,json]
----
{
	"status": "OK",
	"message": "User newUser is created successfully."
}
----
--

[Post] /users/{userName}/changePassword::
+
--
Changes the password of a specified user.

.Request parameters
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`userName`
|Name of the user whose password to be changed
|String
|Required
|===

.Example request command
[source]
----
curl -u 'wbadmin:wbadmin' -H "accept: application/json" -H "content-type: application/json" -X POST "http://localhost:8080/business-central/rest/users/titan/changePassword" -d newpassword
----

.Example server response (JSON)
[source,json]
----
{
    "status": "OK",
    "message": "Password for newUser has been updated successfully."
}
----
--

[DELETE] /users/{userName}::
+
--
Deletes a specified user from {CENTRAL}.

.Request parameters
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`userName`
|Name of the user to be deleted
|String
|Required
|===

.Example server response (JSON)
[source,json]
----
{
    "status": "OK",
    "message": "User newUser is deleted successfully."
}
----
--

[POST] /users/{userName}/groups::
+
--
Updates the groups assigned to a specified user.

.Request parameters
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`userName`
|Name of the user whose assigned groups to be updated
|String
|Required
|===

.Example request body (JSON)
[source,json]
----
[
	"newGroup"
]
----

.Example server response (JSON)
[source,json]
----
{
    "status": "OK",
    "message": "Groups [newGroup] are assigned successfully to user wbadmin"
}
----
--

[POST] /users/{userName}/roles::
+
--
Updates the roles assigned to a specified user.

.Request parameters
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`userName`
|Name of the user whose assigned roles to be updated
|String
|Required
|===

.Example request body (JSON)
[source,json]
----
[
	"admin"
]
----

.Example server response (JSON)
[source,json]
----
{
    "status": "OK",
    "message": "Roles [admin] are assigned successfully to user wbadmin"
}
----
--
