[id="con-kogito-microservices-on-ocp_{context}"]
= {KOGITO} on {OPENSHIFT}

You can deploy {KOGITO} microservices on {OPENSHIFT} for cloud implementation. In this architecture, {KOGITO} microservices are deployed as OpenShift pods that you can scale up and down individually to provide as few or as many containers as required for a particular service. You can use standard OpenShift methods to manage the pods and balance the load.

To help you deploy your microservices on OpenShift, {KOGITO} provides an operator and a command-line interface (CLI):

* *{KOGITO} Operator*: An operator that guides you through the deployment process. The {KOGITO} Operator is based on the https://sdk.operatorframework.io/[Operator SDK] and automates many of the deployment steps for you. For example, when you give the operator a link to the Git repository that contains your application, the operator can automatically configure the components required to build your project from source and deploy the resulting services.
* *{PRODUCT} command-line interface (CLI)*: A CLI tool that enables you to interact with the {KOGITO} Operator for deployment tasks. The {KOGITO} CLI also enables you to deploy {KOGITO} microservices from source instead of relying on custom resources and YAML files. You can use the {KOGITO} CLI as a command-line alternative for deploying {KOGITO} microservices without the {OPENSHIFT} web console.
