[id="proc-kogito-microservices-deploying-on-ocp-kogito-cli_{context}"]
= Deploying {KOGITO} microservices on OpenShift using the {KOGITO} CLI

The {KOGITO} command-line interface (CLI) enables you to interact with the {KOGITO} Operator for deployment tasks. The {KOGITO} CLI also enables you to deploy {KOGITO} microservices from source instead of relying on custom resources and YAML files. You can use the {KOGITO} CLI as a command-line alternative for deploying {KOGITO} microservices without the {OPENSHIFT} web console.

.Prerequisites
* The `oc` OpenShift CLI is installed and you are logged in to the relevant OpenShift cluster. For `oc` installation and login instructions, see the https://access.redhat.com/documentation/en-us/openshift_container_platform/4.2/html/cli_tools/openshift-cli-oc[OpenShift documentation].
* You have OpenShift permissions to create resources in a specified namespace.
* (Quarkus only) The `pom.xml` file of your {PRODUCT} project contains the following dependency for the https://quarkus.io/guides/microprofile-health[Quarkus `smallrye-health` extension]. This extension enables the https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes[liveness and readiness probes] that are required for Quarkus-based projects on OpenShift.
+
.SmallRye Heath dependency for Quarkus applications on OpenShift
[source,xml]
----
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-smallrye-health</artifactId>
</dependency>
----

.Procedure
. Go to the https://github.com/kiegroup/kogito-operator/releases[`kogito-operator`] releases page in GitHub and download the latest version of the `kogito-cli-_RELEASE_` binary file that is specific to your operating system.
. Extract the `kogito-cli-_RELEASE_` binary file to a local directory:
+
--
* On Linux or Mac: In a command terminal, navigate to the directory where you downloaded the `kogito-cli-_RELEASE_` binary file and enter the following command to extract the contents:
+
.Extract the {KOGITO} CLI distribution
[source,subs="attributes+,+quotes"]
----
$ tar -xvf kogito-cli-_RELEASE_.tar.gz
----

* On Windows: In your file browser, navigate to the directory where you downloaded the `kogito-cli-_RELEASE_` binary file and extract the ZIP file.

The `kogito` executable file appears.
--
. Move the extracted `kogito` file to an existing directory in your `PATH` variable:
+
--
* On Linux or Mac: In a command terminal, enter the following command:
+
.Move the `kogito` file
[source,subs="attributes+,+quotes"]
----
$ cp /__PATH_TO_KOGITO__ /usr/local/bin
----

* On Windows: Update the relevant `PATH` environment variables in your system settings to include the path to the {KOGITO} CLI folder. For example, on Windows 10, go to *Settings* -> *System Info* -> *Advanced System Settings* -> *Advanced* -> *Environment Variables* and in the *User* or *System* variables, add the path for the {KOGITO} CLI folder to the `PATH` variable. Close and reopen your Windows command prompt to apply the changes.
--
. With the {KOGITO} CLI now installed, enter the following commands to deploy your {KOGITO} microservices on OpenShift from source:
+
--
NOTE: You must be logged in to the relevant OpenShift cluster using the `oc login` command.

.Example {KOGITO} microservice deployment from existing namespace
[source,subs="attributes+,+quotes"]
----
// Uses the provisioned namespace in your OpenShift cluster
$ kogito use-project __PROJECT_NAME__

// Deploys a new {PRODUCT} service from a Git source
$ kogito deploy-service example-quarkus https://github.com/kiegroup/kogito-examples --context-dir process-quarkus-example
----

The {KOGITO} Operator uses the default branch in the specified Git repository, usually `master`.

NOTE: The first time that you use the {KOGITO} CLI to interact with a project or service, the {KOGITO} Operator is automatically installed and used to execute the relevant tasks.

Alternatively, you can generate a new namespace in your cluster during deployment:

.Example {KOGITO} microservice deployment from new namespace
[source,subs="attributes+,+quotes"]
----
// Creates a new namespace in your cluster
$ kogito new-project __NEW_PROJECT_NAME__

// Deploys a new {PRODUCT} service from a Git source
$ kogito deploy-service example-quarkus https://github.com/kiegroup/kogito-examples --context-dir process-quarkus-example
----

You can also combine the commands to create the namespace and deploy the microservice using the following abbreviated syntax:

.Abbreviated command for {KOGITO} microservice deployment
[source,subs="attributes+,+quotes"]
----
$ kogito deploy-service example-quarkus https://github.com/kiegroup/kogito-examples --context-dir process-quarkus-example --project __PROJECT_NAME__
----
--
