[id="proc-vscode-extension_{context}"]
= Installing the {PRODUCT} VSCode extension bundle

{PRODUCT} provides a *Red Hat Business Automation Bundle* VSCode extension that enables you to design Decision Model and Notation (DMN) decision models, Business Process Model and Notation (BPMN) 2.0 business processes, and test scenarios directly in VSCode. VSCode is the preferred integrated development environment (IDE) for developing new business applications. {PRODUCT} also provides individual *DMN Editor* and *BPMN Editor* VSCode extensions for DMN or BPMN support only, if needed.

IMPORTANT: The editors in the VSCode extension are only partially compatible with the editors in the {CENTRAL}, and several {CENTRAL} features are not supported. If you want to use such features in the VSCode, you can raise a request for a required feature.

.Prerequisites
* Latest stable version of https://code.visualstudio.com/[VSCode] is installed.

.Procedure
. In your VSCode IDE, select the *Extensions* menu option and search for *Red Hat Business Automation Bundle* for DMN, BPMN, and test scenario file support.
+
For DMN or BPMN file support only, you can also search for the individual *DMN Editor* or *BPMN Editor* extensions.
. When the *Red Hat Business Automation Bundle* extension appears in VSCode, select it and click *Install*.
. For optimal VSCode editor behavior, after the extension installation is complete, reload or close and re-launch your instance of VSCode.

After you install the VSCode extension bundle, any `.dmn`, `.bpmn`, or `.bpmn2` files that you open or create in VSCode are automatically displayed as graphical models. Additionally, any `.scesim` files that you open or create are automatically displayed as tabular test scenario models for testing the functionality of your business decisions.

If the DMN, BPMN, or test scenario modelers open only the XML source of a DMN, BPMN, or test scenario file and displays an error message, review the reported errors and the model file to ensure that all elements are correctly defined.

NOTE: For new DMN or BPMN models, you can also enter `dmn.new` or `bpmn.new` in a web browser to design your DMN or BPMN model in the online modeler. When you finish creating your model, you can click *Download* in the online modeler page to import your DMN or BPMN file into your {PRODUCT} project in VSCode.

Before you can begin developing BPMN and DMN models in VSCode, you need to create a Maven project where you can build your assets and any other related resources for your application. For more information about creating Maven project, see {URL_GETTING_STARTED}[Getting started with {PRODUCT}].
